// <auto-generated />
namespace PRO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class review_moderator_allow_nulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(review_moderator_allow_nulls));
        
        string IMigrationMetadata.Id
        {
            get { return "202008041438181_review_moderator_allow_nulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
