// <auto-generated />
namespace PRO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newGameLanguageRelation3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newGameLanguageRelation3));
        
        string IMigrationMetadata.Id
        {
            get { return "202007272054351_newGameLanguageRelation3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
