namespace PRO.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SampleData3 : DbMigration
    {
        public override void Up()
        {
            Sql(@"
            INSERT INTO [dbo].[AspNetUsers] ([Id], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName]) VALUES (N'5eb5bc6c-173f-4180-aca8-15493310fce2', N'artur@a.pl', 0, N'ABr96KZkKJmwO1/g2tYbMOhxs1sz5Biw1pyhMGUetb4qAymNk8zVAPXBRx6Ep3fjIA==', N'3635fa67-7d1b-4b35-aa54-1f7a63610f14', NULL, 0, 0, NULL, 0, 0, N'Artur')
            INSERT INTO [dbo].[AspNetUsers] ([Id], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName]) VALUES (N'd800af38-12ff-439a-979e-581590a99dba', N'stefan@a.pl', 0, N'APSCzQCBQayLf0Xcd16eFDPfYxVwxQSB012CYuDljqQDGouhSL62ijPenY4vEDemsw==', N'a5b66d4a-d98a-4d1c-bc71-dfae1f4990a2', NULL, 0, 0, NULL, 0, 0, N'stefan')
            ");

            Sql(@"
            SET IDENTITY_INSERT [dbo].[Users] ON
            INSERT INTO[dbo].[Users] ([Id], [RegisterDate], [Description], [IsActive], [IsPublic], [ImageId], [UserId]) VALUES(10, N'2012-02-20 00:00:00', NULL, 1, 1, NULL, N'd800af38-12ff-439a-979e-581590a99dba')
            INSERT INTO[dbo].[Users] ([Id], [RegisterDate], [Description], [IsActive], [IsPublic], [ImageId], [UserId]) VALUES(11, N'2021-01-01 00:00:00', NULL, 1, 0, NULL, N'5eb5bc6c-173f-4180-aca8-15493310fce2')
            SET IDENTITY_INSERT[dbo].[Users] OFF
            ");


            Sql(@"
            SET IDENTITY_INSERT [dbo].[UserLists] ON
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(1, N'2012-02-20 00:00:00', 'Dobre',1,9,1)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(2, N'2012-02-20 00:00:00', 'Kiepskie',1,9,2)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(3, N'2012-02-20 00:00:00', 'Kupiæ',1,9,3)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(4, N'2012-02-20 00:00:00', 'Gram',1,9,4)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(5, N'2012-02-20 00:00:00', 'Ukoñczone',1,7,1)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(6, N'2012-02-20 00:00:00', 'Porzucone',1,7,2)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(7, N'2012-02-20 00:00:00', 'Planowane',1,7,3)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(8, N'2012-02-20 00:00:00', 'Ukoñczone',1,10,1)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(9, N'2012-02-20 00:00:00', 'Porzucone',1,10,2)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(10, N'2012-02-20 00:00:00', 'Ukoñczone',1,11,1)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(11, N'2012-02-20 00:00:00', 'Porzucone',1,11,2)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(12, N'2012-02-20 00:00:00', 'Planowane',1,11,3)
            INSERT INTO[dbo].[UserLists] ([Id], [CreatedDate], [Name], [IsPublic], [UserId], [ListTypeId]) VALUES(13, N'2012-02-20 00:00:00', 'Grane',1,11,4)
            SET IDENTITY_INSERT[dbo].[UserLists] OFF
            ");


            Sql(@"
            SET IDENTITY_INSERT [dbo].[GameLists] ON
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(1, N'2012-02-20 00:00:00', 9, 8, 1, 1, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(2, N'2012-02-20 00:00:00', 15, 9, 1, 2, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(3, N'2012-02-20 00:00:00', 26, 5, 2, 10, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(4, N'2012-02-20 00:00:00', 24, 4, 4, 8, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(5, N'2012-02-20 00:00:00', 17, 6, 4, 9, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(6, N'2012-02-20 00:00:00', 12, 8, 5, 1, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(7, N'2012-02-20 00:00:00', 0, NULL, 7, 1, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(8, N'2012-02-20 00:00:00', 0, NULL, 7, 2, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(9, N'2012-02-20 00:00:00', 0, NULL, 7, 3, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(10, N'2012-02-20 00:00:00', 8, 1, 8, 7, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(11, N'2012-02-20 00:00:00', 1, 7, 9, 7, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(12, N'2012-02-20 00:00:00', 3, 10, 9, 9, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(13, N'2012-02-20 00:00:00', 6, 10, 9, 8, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(14, N'2012-02-20 00:00:00', 42, 2, 9, 11, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(15, N'2012-02-20 00:00:00', 15, 10, 9, 10, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(16, N'2012-02-20 00:00:00', 0, NULL, 11, 11, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(17, N'2012-02-20 00:00:00', 0, NULL, 11, 13, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(18, N'2012-02-20 00:00:00', 0, NULL, 11, 14, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(19, N'2012-02-20 00:00:00', 0, NULL, 11, 10, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(20, N'2012-02-20 00:00:00', 0, NULL, 11, 12, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(21, N'2012-02-20 00:00:00', 0, NULL, 11, 3, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(22, N'2012-02-20 00:00:00', 10, 9, 12, 1, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(23, N'2012-02-20 00:00:00', 20, 4, 12, 2, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(24, N'2012-02-20 00:00:00', 14, NULL, 4, 5, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(25, N'2012-02-20 00:00:00', 52, 7, 8, 1, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(26, N'2012-02-20 00:00:00', 742, 9, 8, 2, NULL)
            INSERT INTO[dbo].[GameLists] ([Id], [AddedDate], [HoursPlayed], [PersonalScore], [UserListId], [GameId], [EditedDate]) VALUES(27, N'2012-02-20 00:00:00', 111, 8, 4, 3, NULL)
            SET IDENTITY_INSERT[dbo].[GameLists] OFF
            ");

            Sql(@"
            SET IDENTITY_INSERT [dbo].[Reviews] ON
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(1, N'Gra wci¹ga, jest ogromna iloœæ zadañ które gracz mo¿e wykonaæ i polecam j¹ sprawdziæ. Jak komuœ nie zadzia³a to szybki zwrot na Steamie i powrót za pó³ roku po patchach. Osobiœcie nie myœla³em, ¿e gra CDPR mnie tak wci¹gnie, ale mam ju¿ za sob¹ kilkanaœcie godzin a zrobi³em mo¿e 10% fabu³y. Gra jest na wiele godzin, mo¿e do koñca lockdownu j¹ przejdê :D',N'2017-05-20 00:00:00', 4, 7, 8, NULL,7,9,1,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(2, N'Zanim mo¿e zacznê piaæ z zachwytu jaka to nie jest wspania³a gra, to myœlê ¿e warto wyt³umaczyæ dlaczego tak twierdzê. Przede wszystkim Cyberpunk, od momentu zapowiedzi w 2013, ani trochê mnie nie zainteresowa³. Nie œledzi³em ¿adnych newsów na temat powstawania gry, nie ogl¹da³em materia³ów promocyjnych, ani nie ogl¹da³em pierwszych pokazów gameplay. Grê kupi³em spontanicznie oko³o dwa tygodnie przed premierê, nastawiaj¹c siê na ni¹ bardzo neutralnie, œmiej¹c siê przy tym z wyolbrzymionych oczekiwañ i hype na temat tej gry. Przechodz¹c jednak do recenzji...', N'2017-02-20 00:00:00', 6, 7, 6, NULL,5,9,2,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(3,  N'Po 18 godzinach i kilku hotfixach muszê przyznaæ, ¿e gra naprawdê jest coraz mniej zbugowana. Co do fabu³y nie mo¿na siê doczepiæ - wci¹ga i wzbudza emocje. Detale w tej grze stoj¹ na najwy¿szym poziomie, przez co czêsto zamiast skupiæ siê na g³ównych questach, wolê czasami pochodziæ po mieœcie i porobiæ coœ bardziej oderwanego od ci¹gu fabu³y. Genialna gra, s³ów brak by opisaæ wra¿enia po tych kilkunastu godzinach gry. Kto siê waha - niech siê przemo¿e i kupi tê grê. To najlepiej wydane 200 z³ na grê w moim ¿yciu.',N'2017-03-10 00:00:00', 7, 7, 7, NULL,7,9,3,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(4,  N'Najprawdopodobniej jedna z najlepszych gier jakie powsta³y. Idealnie pokazuje brudny cyberpunkowy œwiat przez co wczucie siê w ca³y ten klimat przychodzi z ³atwoœci¹. Gra ma swoje problemy (liczne bugi, niektóre bardziej upierdliwe, drugie mniej) ale fabularnie - jest miazga. Mimo wszystko, warto poczekaæ na ³atki które naprawi¹ zdecydowan¹ wiêkszoœæ bugów, ale nie zmienia to faktu ¿e dostaliœmy coœ, na co warto by³o czekaæ.',N'2012-09-20 00:00:00', 9, 9, 5, NULL,8,9,5,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(5, N'Myœlê ¿e po 85 godzinach spêdzonych w Night City, mogê wreszcie opisaæ jak czujê siê z nowym tworem CD Projekt Red zwanym Cyberpunk 2077 bazowanym na papierowej grze fabularnej Cyberpunk 2020 stworzonej przez Mikea Pondsmitha. Po oœmiu latach w koñcu doczekaliœmy siê premiery gry na któr¹ czeka³a bardzo du¿¹ czêœæ graczy.',N'2012-05-20 00:00:00',  10, 10, 9, NULL,9,9,9,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(6,  N'Na pocz¹tku myœla³em ,¿e to ¿art jak gra jest zabugowana no i jak dzia³a ale... no i w³aœnie jest to ale po przestawieniu myœlenia i wg³êbieniu siê w fabu³ê ciê¿ko by³o mi oderwaæ siê od fabu³y zarówno g³ównej jak i pobocznej. Jedna z lepiej napisanych historii. Czy gra mog³aby byæ lepiej zoptymalizowana - jasne, czy powinno byæ mnie bugów i glitch - jasne.',N'2012-01-20 00:00:00', 7, 5, 4, NULL,5,10,1,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(7,  N'Cyberpunk 2077. Je¿eli o mnie chodzi nie czu³em jakiegoœ mocnego hajpu na tê grê, nie czeka³em na ni¹ jakoœ mocno, nawet nie planowa³em jej kupiæ, a tym bardziej na premierê, bo nie jestem zwolennikiem kupowania gier zaraz po ich wyjœciu, nie zapoznaj¹c siê wczeœniej z opiniami i recenzjami danej gry, jedyne co przyci¹ga³o moj¹ uwagê to mocna kampania marketingowa i to ¿e jest to gra polskiego studia CD projekt',N'2015-05-25 00:00:00', 6, 6, 3, N'2012-02-21 00:00:00',2,10,2,8)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(8,  N'Gra stawia nowe filary w gamedevie, jeœli chodzi o wertykaln¹ warstwê fabularn¹, czy te¿ oprawê audiowizualn¹. Ogrywanie jej na RayTracingu to istne wzrokowe wodotryski, ale nie ka¿dy portfel jest na tyle gruby, ¿eby ograæ to w stabilnych 60 klatkach. Natomiast gra ma potê¿ne wady, których nie jestem w stanie wybaczyæ developerom.',N'2012-06-01 00:00:00', 1, 2, 1, N'2012-02-21 00:00:00',2,10,3,8)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(9,  N'S¹dzê, ¿e po przegraniu 160h+ mogê w koñcu siê wypowiedzieæ. Gra ma b³êdy. Ale nie s¹ to b³êdy niszcz¹ce rozrywkê, w najgorszym przypadku wystarczy wgraæ save i po sprawie. tym bardziej, ¿e sejwy wgrywaj¹ siê w parenaœcie-paredziesi¹t sekund. Pod wzglêdem otwartego œwiata nie to parê rzeczy kuleje',N'2018-12-20 00:00:00', 6, 8, 7, NULL,7,10,11,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(10,  N'Zdecydowanie polecam ale nie bêdê k³amaæ ¿e gra na obecn¹ chwile jest idealna, zarzuty w kwestii wiêkszych lub mniejszych b³êdów s¹ jak najbardziej prawdziwe, ale to wci¹¿ dobrze wykreowany i zbudowany œwiat z dobr¹ histori¹ i œwietnymi postaciami. Moja ocena 7/10. Przysz³e patche naprawi¹ grê i bêdzie 10/10 :)',N'2012-11-20 00:00:00', 9, 7, 9, NULL,7,10,12,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(11,  N'Dla tych co siê zastanawiaj¹ nad kupnem gry na szybko..., jeœli nie przeszkadzaj¹ Ci wizualne b³êdy, a Twój komputer daje przys³owiowo radê, to bierz i nie zastanawiaj siê. Ja osobiœcie w trakcie 50h gry nie uœwiadczy³em ¿adnego crasha, powa¿nych b³êdów lub zbugowanych questów. A nawet jeœli by siê zdarzy³o to dla mnie ¿aden problem dopóki nie jest to czêste.',N'2019-10-20 00:00:00', 5, 5, 4, N'2012-02-21 00:00:00',7,11,1,8)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(12,  N'S¹ drobne bugi w grze, najczêœciej zdarza³o mi siê, ¿e nie mog³em podnosiæ ró¿nych itemów. Postacie jak i auta kawa³ek siê teleportuj¹. Animacje postaci ludzi¹ przeskakiwaæ tzn. jedna po drugiej nie s¹ p³ynne.',N'2020-02-20 00:00:00', 7, 2, 3, NULL,5,11,2,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(13,  N'Obcowanie z t¹ gr¹ to sinusoida oceny. Od pocz¹tkowego zachwytu (grafik¹ i klimatem), przez rozczarowanie (odkrywanie elementów, które s¹ strasznie s³abe), realizm (wady nie przes³aniaj¹ zalet), a¿ po zakochanie (z¿ycie z postaciami i si³a emocji przes³aniaj¹ biedê innych elementów)',N'2014-02-20 00:00:00', 5, 7, 6, N'2012-02-21 00:00:00',4,11,5,8)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(14,  'Zdecydowanie siê nie zawiod³em, klimaty i oprawa gry jest dok³adnie taka jak sobie wyobra¿a³em. Rozgrywka bardzo przyjemna zdecydowanie nie bêdziecie siê nudziæ na mapie jest mnóstwo aktywnoœci. Mapa jest œwietnie zrobiona Night City wygl¹da ja faktyczna cyberpunkowa metropolia. Niestety na t¹ chwilê ma du¿e problemy z optymalizacj¹ i jest sporo b³êdów ale wierzê ¿e za jakiœ czas twórcy to naprawi¹. Gra zdecydowanie warta polecenia.',N'2018-02-20 00:00:00', 8, 7, 7, NULL,8,11,7,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(15,  'Mimo kilku ma³ych problemów nie przeszkodzi³o mi to z cieszenia siê z gry. Przez 6 godzin grania musia³em wczytaæ checkpoint tylko raz przez jednego buga. Nowe patche mog¹ pomóc z optymalizacj¹ wiêc polecam na nie czekaæ ( Patch 1.04 w³aœnie wiele problemów z optymalizacj¹ naprawi³ )',N'2016-03-20 00:00:00', 5, 7, 6, NULL,10,7,1,NULL)
            INSERT INTO[dbo].[Reviews] ([Id],[Content], [ReviewDate], [GraphicsScore], [StoryScore], [MusicScore], [EditDate],[GameplayScore],[UserId],[GameId],[ModeratorId]) VALUES(16,  'Uwaga uwaga, gra ma bugi, kto by siê spodziewa³. Dobra to teraz o grze. Jest spoko, krótka, ale sporo zadañ pobocznych. customizacja jest doœæ s³aba, ale dobieranie zdolnoœci i ogólnie aspekty RPG typu drzewka, statystyki broni itp s¹ bardzo mocne. Grafika jest dobra, nawet na œrednio niskich ustawieniach. Na pierwszym patchu w czasie jednej z misji pod koniec drugiego aktu gra siê wysypywa³a, ale teraz nie ma wiêkszych problemów. Fabu³a jest okej',N'2012-02-20 00:00:00', 7, 8, 7, NULL,8,8,1,NULL)
            SET IDENTITY_INSERT[dbo].[Reviews] OFF
            ");

            Sql(@"
            SET IDENTITY_INSERT [dbo].[Articles] ON
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(1,N'Tytu³ artyku³u', N'2019-06-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 1, 7, 1,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(2,N'Tytu³ artyku³u', N'2020-12-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 2, 7, 1,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(3,N'Tytu³ artyku³u', N'2020-02-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 3, 7, 1,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(4,N'Tytu³ artyku³u', N'2019-11-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 4, 7, 1,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(5,N'Tytu³ artyku³u', N'2018-10-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 5, 7, 1,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(6,N'Tytu³ artyku³u', N'2019-07-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 6, 7, 2,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(7,N'Tytu³ artyku³u', N'2017-03-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 8, 9, 2,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(8,N'Tytu³ artyku³u', N'2017-01-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 10, 9, 2,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(9,N'Tytu³ artyku³u', N'2020-04-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 11, 9, 2,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(10,N'Tytu³ artyku³u', N'2020-05-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 12, 9, 3,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            INSERT INTO[dbo].[Articles] ([Id], [Title],[PublishedDate], [SourceLink], [Content], [ImageId], [GameId], [UserId],[ArticleTypeId],[IsActive],[Preview]) 
                VALUES(11,N'Tytu³ artyku³u', N'2020-08-20 00:00:00','link',N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', NULL, 13, 9, 3,1,N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.')
            SET IDENTITY_INSERT[dbo].[Articles] OFF
            ");
        }
        
        public override void Down()
        {
        }
    }
}
