// <auto-generated />
namespace PRO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Game_Gamelist_ImageType_ModelCorrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Game_Gamelist_ImageType_ModelCorrections));
        
        string IMigrationMetadata.Id
        {
            get { return "202103111508002_Game_Gamelist_ImageType_ModelCorrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
